### ISSUE TITLE
Lists  - remove(), removeAll()

### ISSUE THREAD

**Issue by GHCFOSS** [GHCFOSS/DataVisualizer-JAVA#20]
List data structure implementation is currently incomplete. Provide implementation for:

Boolean remove(Integer element);
void removeAll();
Integer size();

**Comment by zunman** [comment]
remove(int element): search and remove specified element. return true if element removed successfully. return false if element not found.
removeAll(): remove all elements from list
size(): return count of elements in list

**Comment by zunman** [comment]
using built-in ArrayList functions
